version: 2
updates:
  # Pacotes npm/pnpm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50
    allow:
      - dependency-type: "all"

  # Dockerfiles
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
