name: Package
on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: NPM_TOKEN
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmjs.org/
          npm install --legacy-peer-deps
      - name: Build package
        run: npm run build
      - name: Publish to npm
        if: github.ref == 'refs/heads/main'
        run: |
          test -n "$NODE_AUTH_TOKEN" || (echo "NPM_TOKEN is not set" && exit 1)
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm whoami
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
